#ifndef PRJMYSTDCPPLIB_GLOBAL_H
#define PRJMYSTDCPPLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRJMYSTDCPPLIB_LIBRARY)
#  define PRJMYSTDCPPLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRJMYSTDCPPLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRJMYSTDCPPLIB_GLOBAL_H
